name: learn-github-actions
run-name: ${{ github.actor }} triggered ${{ github.event.repository.name }}-${{ github.base_ref || github.ref_name }}
on: 
    push:
        
    pull_request:
        
    workflow_call:

env:
    WEBAPP_REF: ${{ vars.WEBAPP_REF || github.base_ref || github.ref_name || 'main' }}
    REPO_NAME: ${{ github.event.repository.name }}
    SERVICE_NAME: ${{ github.event.repository.name }}-${{ github.base_ref || github.ref_name || 'NO_BASE_REF' }}
    TARGET_SERVER: ${{ vars.TARGET_SERVER }}
    SSH_PEM: ${{ secrets.SSH_PEM }}
    
jobs:
  Deploy_Service:
    name: Deploy ${{ github.event.repository.name }}-${{ github.base_ref || github.ref_name || 'ERROR' }}
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref || 'main' }}
    
    steps:
    - name: Workflow Target Summary
      run: |
        echo '## ${{ env.SERVICE_NAME }} on ${{ vars.PORT }} 🚀 [link](https://${{ vars.TARGET_SERVER }}:${{ vars.PORT }}/swagger/index.html)' >> $GITHUB_STEP_SUMMARY
        echo '### GH environment: ${{ github.base_ref || 'main' }}' >> $GITHUB_STEP_SUMMARY

    - name: Fetch Service '${{ github.event.repository.name }}'
      uses: actions/checkout@v4
      with:
        path: ${{ env.REPO_NAME }}
    
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
