name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_call:

env:
    WEBAPP_REF: ${{ vars.WEBAPP_REF || github.base_ref || '??' }}
    REPO_NAME: ${{ github.event.repository.name }}
    SERVICE_NAME: ${{ github.event.repository.name }}-${{ github.base_ref || 'NO_BASE_REF' }}
    TARGET_SERVER: ${{ vars.TARGET_SERVER }}
    SSH_PEM: ${{ secrets.SSH_PEM }}
    
jobs:
  Deploy_Service:
    name: Deploy ${{ github.event.repository.name }}-${{ github.base_ref || 'NO_BASE_REF' }}
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref || 'NO_BASE_REF_FOR_ENVIRONMENT' }}
    
    steps:
    - name: Workflow Target Summary
      run: |
        echo '## ${{ env.SERVICE_NAME }} on ${{ vars.PORT }} 🚀 [link](https://${{ vars.TARGET_SERVER }}:${{ vars.PORT }}/swagger/index.html)' >> $GITHUB_STEP_SUMMARY
        echo '### ${{ github.base_ref || 'NO_BASE_REF_FOR_ENVIRONMENT' }}' >> $GITHUB_STEP_SUMMARY

    - name: Fetch Service '${{ github.event.repository.name }}'
      uses: actions/checkout@v4
      with:
        path: ${{ env.REPO_NAME }}